services:
  carddung:
    build: .
    container_name: carddung
    ports:
      - "3000:3000"
    restart: unless-stopped

  carddung-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: carddung-server
    ports:
      - "4000:4000"
    volumes:
      - cards-data:/server/data
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: admin.Dockerfile
    container_name: carddung-admin
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - carddung
      - carddung-server
      - admin
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: certbot certonly --webroot -w /var/www/certbot --domain game.you-argument.ru --email admin@you-argument.ru --agree-tos --non-interactive

volumes:
  certbot-conf:
  certbot-www:
  cards-data:
